[env]
platform = espressif32
board = rymcu-esp32-s3-devkitc-1
framework = arduino
lib_deps = 
	https://github.com/starfactorypixel/Library_CUtils
	https://github.com/starfactorypixel/PixelLoggerLibrary
	https://github.com/starfactorypixel/Library_DrakePin
	https://github.com/starfactorypixel/Library_DrakeScript
	https://github.com/starfactorypixel/Library_PixelSPI
;board_build.partitions = huge_app.csv
monitor_port = COM4
monitor_speed = 500000
upload_port = COM4
upload_speed = 921600
debug_tool = esp-builtin
build_flags = 
	-D ARDUINO_USB_MODE=1
	-D ARDUINO_USB_CDC_ON_BOOT=1
	-D USE_EMULATOR
;	-D NO_CAN_SEND

[env:Debug]
build_type = debug
build_flags = 
	${env.build_flags}
	-DCORE_DEBUG_LEVEL=4
	-D DEBUG

[env:Release]
build_type = release
build_unflags = 
build_flags = 
	${env.build_flags}
	-DCORE_DEBUG_LEVEL=0

